import type { Metadata } from 'next'
import './globals.css'

const siteUrl = 'https://andysottiaux.com'

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: 'Andy Sottiaux - Engineer & Founder',
    template: '%s | Andy Sottiaux'
  },
  description: 'Engineer & Founder bridging aerospace hardware and production software. Building UAV systems and autonomy at AVX Aircraft. Shipping 10+ iOS apps and web platforms at HatchingPoint.',
  keywords: [
    'Andy Sottiaux',
    'Andrew Sottiaux',
    'Senior Engineer',
    'Aerospace Engineer',
    'UAV Systems',
    'iOS Developer',
    'Swift Developer',
    'AVX Aircraft',
    'Bell Flight',
    'HatchingPoint',
    'Rotor Design',
    'Autonomy',
    'ROS2',
    'Full Stack Developer',
    'React',
    'Next.js',
    'Fort Worth',
    'Texas',
  ],
  authors: [{ name: 'Andy Sottiaux', url: siteUrl }],
  creator: 'Andy Sottiaux',
  publisher: 'Andy Sottiaux',
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: siteUrl,
    siteName: 'Andy Sottiaux',
    title: 'Andy Sottiaux - Engineer & Founder',
    description: 'Engineer & Founder bridging aerospace hardware and production software. Building UAV systems at AVX Aircraft. Shipping 10+ iOS apps at HatchingPoint.',
    // Images auto-generated by app/opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Andy Sottiaux - Engineer & Founder',
    description: 'Engineer & Founder bridging aerospace hardware and production software. Building UAV systems at AVX Aircraft. Shipping 10+ iOS apps at HatchingPoint.',
    // Images auto-generated by app/twitter-image.tsx
    creator: '@andysottiaux',
  },
  alternates: {
    canonical: siteUrl,
  },
  category: 'technology',
  verification: {
    // Add your Google Search Console verification code here after setup
    // google: 'your-verification-code',
  },
}

// JSON-LD Structured Data for Person
const jsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Person',
  name: 'Andy Sottiaux',
  alternateName: 'Andrew Sottiaux',
  url: siteUrl,
  image: `${siteUrl}/images/profile.jpg`,
  jobTitle: 'Engineer & Founder',
  description: 'Engineer and founder bridging aerospace hardware and production software. Building UAV systems at AVX Aircraft and shipping 10+ iOS apps at HatchingPoint.',
  email: 'andrewsottiaux@gmail.com',
  sameAs: [
    'https://www.linkedin.com/in/andysottiaux',
    'https://github.com/Andy-Sottiaux',
  ],
  worksFor: {
    '@type': 'Organization',
    name: 'AVX Aircraft Company',
    url: 'https://avxaircraft.com'
  },
  alumniOf: [
    {
      '@type': 'CollegeOrUniversity',
      name: 'Texas Tech University',
      url: 'https://www.ttu.edu'
    },
    {
      '@type': 'Organization',
      name: 'Bell Flight'
    },
    {
      '@type': 'Organization',
      name: 'HatchingPoint'
    }
  ],
  knowsAbout: [
    'Software Engineering',
    'Full Stack Development',
    'React',
    'Next.js',
    'TypeScript',
    'Python',
    'Aerospace Software',
    'Entrepreneurship'
  ],
  address: {
    '@type': 'PostalAddress',
    addressRegion: 'Texas',
    addressCountry: 'US'
  }
}

// Additional WebSite structured data for sitelinks search box
const websiteJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  name: 'Andy Sottiaux',
  url: siteUrl,
  description: 'Personal website of Andy Sottiaux - Engineer & Founder',
  author: {
    '@type': 'Person',
    name: 'Andy Sottiaux'
  }
}

// Breadcrumb structured data for better search result display
const breadcrumbJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'BreadcrumbList',
  itemListElement: [
    {
      '@type': 'ListItem',
      position: 1,
      name: 'Andy Sottiaux',
      item: siteUrl
    }
  ]
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        {/* Favicon and Apple icon auto-generated by app/icon.tsx and app/apple-icon.tsx */}
        <meta name="theme-color" content="#1a1a1a" />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }}
        />
      </head>
      <body>
        <a
          href="#about"
          className="sr-only focus:not-sr-only focus:absolute focus:top-4 focus:left-4 focus:z-[100] focus:px-4 focus:py-2 focus:bg-white focus:text-foreground focus:rounded-lg focus:shadow-lg focus:font-medium"
        >
          Skip to main content
        </a>
        {children}
      </body>
    </html>
  )
}
