import type { Metadata } from 'next'
import { Analytics } from "@vercel/analytics/next"
import { SpeedInsights } from "@vercel/speed-insights/next"
import ThemeProvider from '../components/ThemeProvider'
import PortfolioAnalytics from '../components/site/PortfolioAnalytics'
import './globals.css'

const siteUrl = 'https://andysottiaux.com'
const siteTitle = 'Andy Sottiaux — Engineer & Founder'
const siteDescription = 'Engineer and founder building across aerospace, embedded systems, robotics, and production apps. Selected work, engineering decisions, and a live hardware lab.'

function serializeJsonLd(data: unknown) {
  return JSON.stringify(data)
    .replace(/</g, '\\u003c')
    .replace(/>/g, '\\u003e')
    .replace(/&/g, '\\u0026')
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029')
}

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: siteTitle,
    template: '%s | Andy Sottiaux'
  },
  description: siteDescription,
  keywords: [
    'Andy Sottiaux',
    'Andrew Sottiaux',
    'Senior Engineer',
    'Aerospace Engineer',
    'UAV Systems',
    'Embedded Systems',
    'Edge AI',
    'Computer Vision',
    'iOS Developer',
    'Swift Developer',
    'AVX Aircraft',
    'Bell Flight',
    'HatchingPoint',
    'Rotor Design',
    'Autonomy',
    'ROS2',
    'Full Stack Developer',
    'React',
    'Next.js',
    'Dallas',
    'Texas',
  ],
  authors: [{ name: 'Andy Sottiaux', url: siteUrl }],
  creator: 'Andy Sottiaux',
  publisher: 'Andy Sottiaux',
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: siteUrl,
    siteName: 'Andy Sottiaux',
    title: siteTitle,
    description: siteDescription,
    // Images auto-generated by app/opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: siteTitle,
    description: siteDescription,
    // Images auto-generated by app/twitter-image.tsx
    creator: '@andysottiaux',
  },
  alternates: {
    canonical: siteUrl,
  },
  category: 'technology',
  verification: {
    // Add your Google Search Console verification code here after setup
    // google: 'your-verification-code',
  },
}

// JSON-LD Structured Data for Person
const jsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Person',
  name: 'Andy Sottiaux',
  alternateName: 'Andrew Sottiaux',
  url: siteUrl,
  image: `${siteUrl}/images/andy-casual-headshot-2026.webp`,
  jobTitle: 'Engineer & Founder',
  description: siteDescription,
  email: 'andrewsottiaux@gmail.com',
  sameAs: [
    'https://www.linkedin.com/in/andy-sottiaux-593700100/',
    'https://github.com/Andy-Sottiaux',
  ],
  worksFor: {
    '@type': 'Organization',
    name: 'AVX Aircraft Company',
    url: 'https://avxaircraft.com'
  },
  alumniOf: [
    {
      '@type': 'CollegeOrUniversity',
      name: 'Texas Tech University',
      url: 'https://www.ttu.edu'
    },
    {
      '@type': 'Organization',
      name: 'Bell Flight'
    },
    {
      '@type': 'Organization',
      name: 'HatchingPoint'
    }
  ],
  knowsAbout: [
    'Software Engineering',
    'Full Stack Development',
    'React',
    'Next.js',
    'TypeScript',
    'Python',
    'Embedded Systems',
    'Edge AI',
    'Computer Vision',
    'UAV Systems',
    'CAD',
    'Aerospace Software',
    'Entrepreneurship'
  ],
  address: {
    '@type': 'PostalAddress',
    addressRegion: 'Texas',
    addressCountry: 'US'
  }
}

// Additional WebSite structured data for sitelinks search box
const websiteJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  name: 'Andy Sottiaux',
  url: siteUrl,
  description: siteDescription,
  author: {
    '@type': 'Person',
    name: 'Andy Sottiaux'
  }
}

// Breadcrumb structured data for better search result display
const breadcrumbJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'BreadcrumbList',
  itemListElement: [
    {
      '@type': 'ListItem',
      position: 1,
      name: 'Andy Sottiaux',
      item: siteUrl
    }
  ]
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Favicon and Apple icon auto-generated by app/icon.tsx and app/apple-icon.tsx */}
        <meta name="theme-color" content="#121513" />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: serializeJsonLd(jsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: serializeJsonLd(websiteJsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: serializeJsonLd(breadcrumbJsonLd) }}
        />
      </head>
      <body>
        <ThemeProvider>
            <a
              href="#main-content"
              className="sr-only focus:not-sr-only focus:absolute focus:top-4 focus:left-4 focus:z-[100] focus:px-4 focus:py-2 focus:bg-white dark:focus:bg-gray-800 focus:text-foreground focus:rounded-lg focus:shadow-lg focus:font-medium"
            >
              Skip to main content
            </a>
            {children}
        </ThemeProvider>
        <Analytics />
        <PortfolioAnalytics />
        <SpeedInsights />
      </body>
    </html>
  )
}
