import type { Metadata } from 'next'
import './globals.css'

const siteUrl = 'https://andysottiaux.com'

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: 'Andy Sottiaux - Software Engineer & Entrepreneur',
    template: '%s | Andy Sottiaux'
  },
  description: 'Andy Sottiaux is a software engineer and entrepreneur with experience at AVX Aircraft Company and Bell Flight. Specializing in full-stack development, aerospace software, and startup ventures.',
  keywords: [
    'Andy Sottiaux',
    'Andrew Sottiaux',
    'Software Engineer',
    'Entrepreneur',
    'Full Stack Developer',
    'AVX Aircraft',
    'Bell Flight',
    'Aerospace Engineer',
    'Texas Developer',
    'Fort Worth Developer',
    'React Developer',
    'Next.js Developer',
    'HatchingPoint'
  ],
  authors: [{ name: 'Andy Sottiaux', url: siteUrl }],
  creator: 'Andy Sottiaux',
  publisher: 'Andy Sottiaux',
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: siteUrl,
    siteName: 'Andy Sottiaux',
    title: 'Andy Sottiaux - Software Engineer & Entrepreneur',
    description: 'Software engineer and entrepreneur with aerospace industry experience at AVX Aircraft and Bell Flight. Building innovative solutions and leading technical teams.',
    // Images auto-generated by app/opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Andy Sottiaux - Software Engineer & Entrepreneur',
    description: 'Software engineer and entrepreneur with aerospace industry experience at AVX Aircraft and Bell Flight.',
    // Images auto-generated by app/twitter-image.tsx
    creator: '@andysottiaux',
  },
  alternates: {
    canonical: siteUrl,
  },
  category: 'technology',
  verification: {
    // Add your Google Search Console verification code here after setup
    // google: 'your-verification-code',
  },
}

// JSON-LD Structured Data for Person
const jsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Person',
  name: 'Andy Sottiaux',
  alternateName: 'Andrew Sottiaux',
  url: siteUrl,
  image: `${siteUrl}/images/profile.jpg`,
  jobTitle: 'Software Engineer',
  description: 'Software engineer and entrepreneur with experience in aerospace software development at AVX Aircraft Company and Bell Flight.',
  email: 'andrewsottiaux@gmail.com',
  sameAs: [
    'https://www.linkedin.com/in/andysottiaux',
  ],
  worksFor: {
    '@type': 'Organization',
    name: 'AVX Aircraft Company',
    url: 'https://avxaircraft.com'
  },
  alumniOf: [
    {
      '@type': 'Organization',
      name: 'Bell Flight'
    },
    {
      '@type': 'Organization',
      name: 'HatchingPoint'
    }
  ],
  knowsAbout: [
    'Software Engineering',
    'Full Stack Development',
    'React',
    'Next.js',
    'TypeScript',
    'Python',
    'Aerospace Software',
    'Entrepreneurship'
  ],
  address: {
    '@type': 'PostalAddress',
    addressRegion: 'Texas',
    addressCountry: 'US'
  }
}

// Additional WebSite structured data for sitelinks search box
const websiteJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  name: 'Andy Sottiaux',
  url: siteUrl,
  description: 'Personal website of Andy Sottiaux - Software Engineer & Entrepreneur',
  author: {
    '@type': 'Person',
    name: 'Andy Sottiaux'
  }
}

// Breadcrumb structured data for better search result display
const breadcrumbJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'BreadcrumbList',
  itemListElement: [
    {
      '@type': 'ListItem',
      position: 1,
      name: 'Andy Sottiaux',
      item: siteUrl
    }
  ]
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        {/* Favicon and Apple icon auto-generated by app/icon.tsx and app/apple-icon.tsx */}
        <meta name="theme-color" content="#1a1a1a" />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }}
        />
      </head>
      <body>{children}</body>
    </html>
  )
}
